src/app/news/news.component.html, src/app/news/news.component.scss, src/app/project/project.component.html, src/assets/styles/components/filter-bar.scss
Added initial markup and toggle functionality for advanced filter mechanism in the following views:
- projects.component.html
- news.component.html
- support styling (filter-bar.scss)
=> EPIC-1095 - Initial Markup/Toggle Functionality for Advanced Filters

.angular-cli.json, package.json, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.module.ts, src/app/home/home.component.html, src/app/map/config/index.ts, src/app/map/config/map-config.interface.ts, src/app/map/config/map-config.ts, src/app/map/esri-map/esri-map.component.html, src/app/map/esri-map/esri-map.component.scss, src/app/map/esri-map/esri-map.component.spec.ts, src/app/map/esri-map/esri-map.component.ts, src/app/map/main-map/main-map.component.html, src/app/map/main-map/main-map.component.scss, src/app/map/main-map/main-map.component.spec.ts, src/app/map/main-map/main-map.component.ts, src/app/map/map-loader.service.spec.ts, src/app/map/map-loader.service.ts, src/app/map/map.module.ts, src/assets/styles/footer.scss, src/assets/styles/globals.scss, src/assets/styles/header.scss, src/styles.scss, src/tsconfig.app.json, src/tsconfig.spec.json, yarn.lock
* Replace main map with Esri Map component
* Style map and popups like http://mines.nrs.gov.bc.ca/
* Fix project URL in map popups
* Fix linting errors in map component
* Read webmap id from app configuration (environment.ts)
=> EPIC-1039 Main Map Page

src/app/app.module.ts, src/app/home/home.component.html, src/app/models/project.ts, src/app/news/news.component.html, src/app/project-status-filter.pipe.spec.ts, src/app/project-status-filter.pipe.ts, src/app/project-type-filter.pipe.spec.ts, src/app/project-type-filter.pipe.ts, src/app/project/project.component.html, src/app/project/project.component.ts, src/app/services/project.service.spec.ts
- Added Project Type and Status Filter Pipes
- Updated content for news and project list pages (banner text)
- Fixed an incorrect naming convention (selector) on the home page (home.component.html)
- Fixed white space issue on project.component.ts
=> EPIC-1095 - Continued Interface Development

src/app/home/home.component.scss, src/app/news/news.component.html, src/app/news/news.component.scss, src/assets/styles/components/filter-bar.scss
- News and Home components
- Fixed issue with the filter toggle on small devices
=> EPIC-1095 - Styling Fixes for Activities and Updates Sections

src/app/app.module.ts, src/app/models/project.ts, src/app/news/news.component.html, src/app/news/news.component.ts, src/app/project-decision-filter.pipe.ts, src/app/project-decision.pipe.spec.ts, src/app/project/project.component.html, src/app/project/project.component.ts, src/assets/styles/components/buttons.scss, src/assets/styles/components/filter-bar.scss
- Added project decision filter pipes
- Removed status filter pipe reference (not needed as per conversations with stakeholder)
- Minor styling modifications / visual adjustments to the filter bars
=> EPIC-1095 Adding Project Decision Filtering

src/app/news/news.component.html, src/app/project/project.component.html, src/app/services/news.service.ts, src/assets/styles/components/filter-bar.scss, src/assets/styles/components/table.scss, src/assets/styles/themes/default.scss
Additional Fixes:
- fixed incorrect references in news.service.ts
=> EPIC-1095 - Implement Table Sort Indicators

src/app/news/news.component.html, src/app/news/news.component.ts
- Default sort set to 'Date Added'
=> EPIC-1095 Adding default sort to the activities & updates page

src/app/map/config/map-config.ts, yarn.lock
=> NOBUG: Use prod map for all environments

src/app/home/home.component.html, src/app/home/home.component.scss, src/app/map/config/map-config.ts, src/app/map/esri-map/esri-map.component.scss, src/app/map/main-map/main-map.component.html, src/app/map/main-map/main-map.component.scss, src/app/map/main-map/main-map.component.ts, src/app/news/news.component.html, src/app/news/news.component.scss, src/assets/styles/components/esri-map.scss, src/assets/styles/components/hero-banner.scss, src/assets/styles/header.scss, src/assets/styles/layout.scss, src/assets/styles/themes/default.scss, src/styles.scss
General UI clean-up / fixes
- Added menu indicators to header navigation for menus
- Updated / cleaned-up the markup and styling for the home page and activities items
- Added standard page header for the map page
- Updated map popup component styling
=> General UI Improvements / Fixes

.angular-cli.json, src/app/app.component.ts, src/app/services/api.spec.ts, src/app/services/api.ts, src/app/services/email.service.ts, src/app/services/news.service.ts, src/app/services/project.service.ts
- get the API hostname based on the page location (i.e. env)
- corrected activities/news sorting on the Home page and News page
=> EPIC-1211 ENV Switch EPIC-1207 Activities and Updates Sorting

src/app/app.component.html, src/assets/styles/header.scss
- Changing 'Dashboard' to 'My Projects'
- Fixed small sizing/spacing issue with header menu items
=> EPIC-1226 - Updating Main Navigation Menu Items (EAO PUBLIC LAUNCH)

src/app/map/config/map-config.ts, yarn.lock
* Update `yarn.lock` with bootstrap dependencies
=> EPIC-1239 ArcGIS - disable map rotation

src/app/project/project.component.html, src/app/project/project.component.ts
=> Revert "EPIC-1244 EAO Public: fixed crash when accessing proponents."

src/app/project/project.component.html, src/app/project/project.component.ts
=> Incorrect revert of "EPIC-1244 EAO Public: fixed crash when accessing proponents.""

src/app/map/config/map-config.interface.ts, src/app/map/config/map-config.ts, src/app/map/main-map/main-map.component.ts
=> EPIC-1251 ArcGIS - Fix typing errors

src/assets/styles/components/esri-map.scss, src/assets/styles/themes/default.scss
- Fixed an issue where the newest version of the map viewer broke the map tip styling.
=> [EPIC-1257] Update Map Tip Styling to support v.4.5.0

src/app/app.component.html
> Logging in via “sign in” in the footer it does not take me to the siteminder authentication log in page.
- removed 'local/' from sign-in URL
- corrected whitespace in source code
=> [EM-138] (fix)

src/index.html
Turned on IP anonymization for Google Analytics.
- In index.html <head>, added 'anonymize_ip' parameter to gtag <script> & set it to true.
=> Added IP anonymization parameter to Google Analytics tracking script

src/app/app.module.ts, src/app/models/currentphase.ts, src/app/models/project.ts, src/app/phase-filter.pipe.spec.ts, src/app/phase-filter.pipe.ts, src/app/project/project.component.html, src/app/project/project.component.ts
Added a current phase filter for the projects page
=> em-234 added current phase filter for projects page

src/app/home/home.component.html, src/app/news/news.component.html, src/app/news/news.component.scss, src/assets/styles/layout.scss, src/assets/styles/themes/typography.scss
Added <pre> tags on both the home page and news page to support rendering html formatted content.
=> [EM-240] Renter HTML Content in News Items

src/app/app.component.html, src/app/app.component.ts
Previous fix left spinner always displayed and spinning. This fix should resolve that issue.
=> em-141 fixed bug where spinner was always displaying

src/app/map/main-map/main-map.component.scss, src/assets/styles/components/esri-map.scss
I've removed the max-height properties for the popup in an effort to resolve this bug (using the default behavior). 
Additional Fixes
* Fixed a positioning/sizing issue with the page banner height.
=> [EM-158] Additional Fixes for Map Popup Positioning Bug

src/app/project/project.component.html, src/assets/styles/components/filter-bar.scss
Made each filter in the advanced filters on the projects page the same size.
=> em-234 made each filter sized the same on projects page

sonar-runner/build.gradle
=> Updated SonarQube configuration to use better build names.

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/not-found/not-found.component.html, src/app/not-found/not-found.component.spec.ts, src/app/not-found/not-found.component.ts
> 404 Pages Provide no information to users
- Added a basic 404 component with a home button redirect
=> EM-34: basic 404 page added to EPIC

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/project-detail/project-detail-resolver.service.ts, src/app/project-detail/project-detail.component.html, src/app/project-detail/project-detail.component.spec.ts, src/app/project-detail/project-detail.component.ts, src/app/services/api.ts, src/app/services/project.service.ts
Created skeleton for new project details page that is inaccessible through any links. Only accessible using discrete url /p/{project name}.
=> em-327 created skeleton for new project details page

src/app/models/project.ts, src/app/project-detail/project-detail.component.html
Forgot to update the model with the new attributes so I added those
=> em-327 added attributes to model

src/app/project-detail/project-detail.component.ts
Added a null check for proponent. If null added name attribute and set it to an empty string.
=> em-327 added null check for proponent

src/app/app.module.ts, src/app/project-detail/project-detail.component.html, src/app/project-detail/project-detail.component.ts, src/app/recent-activity-filter.pipe.spec.ts, src/app/recent-activity-filter.pipe.ts
Added filter for activities by:
- Name
- Item type
=> em-333 added filters for activities

src/app/map/esri-map/esri-map.component.ts, src/app/map/main-map/main-map.component.ts, src/app/map/map.module.ts, src/app/map/project-map/project-map.component.html, src/app/map/project-map/project-map.component.scss, src/app/map/project-map/project-map.component.spec.ts, src/app/map/project-map/project-map.component.ts, src/app/models/project.ts, src/app/project-detail/project-detail.component.html, src/app/project-detail/project-detail.component.ts
Added the map thumbnail to the project landing page.
=> em-328 added map view to project landing page

src/app/models/project.ts, src/app/project/project.component.html
- Display EA Certificate Decision Date in a new column beside eacDecision on project list page
=> EM-352: Display project decision date on project list page

src/app/project/project.component.scss
- Modified .scss class to display Date property in project list, for mobile viewers.
=> EM-352 .scss hotfix - show 'Date' in mobile view

src/app/project-detail/project-detail.component.html, src/app/project-detail/project-detail.component.scss
As per QA ticket comments:
- Added a card for Project Status
- Fixed map stylings
- Changed title to {{ project name }} Assessment Information
- Changed filter bar placeholder to "Type an Activity Name"
- Fixed general stylings and cleaned up white space
=> em-328 added project status and fixed some stylings

src/app/news/news.component.html, src/app/news/news.component.scss
Fixed an issue in the activities feed where the pre tag was rendering on a single line.
=> Activities Feed Bug Fix

src/app/project-detail/project-detail.component.html
=> em-328 added eacDecision field to view

src/app/order-by.pipe.ts, src/app/project/project.component.html
Changed order by pipe to allow for null values. Puts all null values at the end of the list regardless if sorting by ascending or descending as per a conversation with Jeremy.
=> Em 471 Filter by decision date

src/app/home/home.component.html, src/app/home/home.component.ts, src/app/news/news.component.html, src/app/news/news.component.ts
> Created local variable in controller to store response to api call. Api will no longer be called in the HTML.
=> EM-322-hotfix: removed public reference to private api

Jenkinsfile, Jenkinsfile.dev
Not really sure why it is showing more than the last commit... 😨
=> EM-788: Uplifted Jenkinsfiles to latest standard.

src/app/project/project.component.html
revert project details links to old links
=> em-818 hotfix: revert project details link to old links

src/app/comment-period/comment-period.component.html, src/app/comment-period/comment-period.component.spec.ts, src/app/comment-period/comment-period.component.ts, src/assets/styles/components/tab-nav.scss
Added 'Related Documents' functionality to public comment periods.
Credits to @jeznorth for markup and styling changes.
=> [EM-815] - PCP - Show Related Documentation

src/app/app.module.ts, src/app/comment-period/comment-period.component.html, src/app/comment-period/comment-period.component.scss, src/app/comment-period/comment-period.component.spec.ts, src/app/comment-period/comment-period.component.ts, src/app/comment-period/comment-period.module.ts, src/app/comment-period/pcp-info-modal/pcp-info-modal.component.html, src/app/comment-period/pcp-info-modal/pcp-info-modal.component.scss, src/app/comment-period/pcp-info-modal/pcp-info-modal.ts, src/app/comment-period/submit-comment-modal/submit-comment-modal.component.html, src/app/comment-period/submit-comment-modal/submit-comment-modal.component.scss, src/app/comment-period/submit-comment-modal/submit-comment-modal.spec.ts, src/app/comment-period/submit-comment-modal/submit-comment-modal.ts, src/app/comment-period/submit-comment-progress-modal/submit-comment-progress-modal.component.html, src/app/comment-period/submit-comment-progress-modal/submit-comment-progress-modal.component.scss, src/app/comment-period/submit-comment-progress-modal/submit-comment-progress-modal.ts, src/app/services/api.spec.ts, src/app/services/api.ts, src/app/services/comment-period.service.ts, src/app/shared/shared.module.ts, src/assets/styles/components/buttons.scss, src/assets/styles/components/card.scss, src/assets/styles/components/file-upload.scss, src/assets/styles/components/form-elements.scss, src/assets/styles/components/lists.scss, src/assets/styles/helpers/helpers.scss, src/assets/styles/layout.scss, src/assets/styles/themes/default.scss, src/assets/styles/themes/typography.scss, src/test.ts
Submit comment functionality finished
- Created validation for form
- Refactored Comment Period code to have partials and it's own module
- Updated tests
=> em-338 submit comment functionality

src/app/app-routing.module.ts, src/app/comment-period/comment-period.component.html, src/app/comment-period/comment-period.component.ts, src/app/project/project.component.html, src/app/services/comment-period.service.ts
=> PCP commits merged: EM-822, EM-815, EM-338

src/app/comment-period/comment-period.component.html, src/app/comment-period/comment-period.component.scss, src/app/comment-period/pcp-info-modal/pcp-info-modal.component.html, src/app/comment-period/submit-comment-modal/submit-comment-modal.component.html, src/app/comment-period/submit-comment-progress-modal/submit-comment-progress-modal.component.html, src/app/comment-period/submit-comment-progress-modal/submit-comment-progress-modal.component.scss, src/app/services/comment-period.service.spec.ts, src/assets/styles/components/file-upload.scss, src/assets/styles/components/spinner.scss, src/assets/styles/themes/default.scss
- Responsive work on the submit comment modals
- Fixed unit test lint errors
=> [EM-842] Submit a Comment - UI Dev

src/app/comment-period/comment-period.component.html, src/app/comment-period/comment-period.component.scss, src/app/comment-period/comment-period.component.ts, src/app/comment-period/pcp-info-modal/pcp-info-modal.component.html, src/app/comment-period/pcp-info-modal/pcp-info-modal.component.scss, src/app/comment-period/submit-comment-modal/submit-comment-modal.component.html, src/app/comment-period/submit-comment-modal/submit-comment-modal.component.scss, src/app/comment-period/submit-comment-modal/submit-comment-modal.ts, src/app/comment-period/submit-comment-progress-modal/submit-comment-progress-modal.component.html, src/app/comment-period/submit-comment-progress-modal/submit-comment-progress-modal.component.scss, src/assets/styles/components/file-list.scss, src/assets/styles/components/file-upload.scss, src/assets/styles/components/form-elements.scss, src/assets/styles/components/modals.scss, src/assets/styles/layout.scss
- Removing prototype text from the comment-period.component.html
- Updating/refactoring selectors in comment-period.component.scss
- Changing the amount of items displayed per page in the comments list (comment-period.component.ts)
- Adding new scss files (file-list.scss, modal.scss)
- Updated markup to use new file-list.scss file (previously was baked into file-upload.scss)
- Few changes to layout.scss to fix inconsistent positioning of the hero banner container element
=> [EM-842] Submit Comment Related Documents UI

src/app/comment-period/comment-period.component.html, src/app/comment-period/comment-period.component.scss, src/app/project-detail/project-detail.component.html, src/assets/styles/components/card.scss, src/assets/styles/components/lists.scss, src/assets/styles/helpers/helpers.scss
- Adding the EA Status badge into the Project Details page
- Small fix for the public comment period page open house list component
=> [EM-841] Add EA Certificate Status to Project Details

src/app/comment-period/comment-period.component.html, src/app/comment-period/comment-period.component.scss, src/app/news/news.component.html, src/app/project-detail/project-detail.component.html
- Fixed an issue with no appScroll in the comment period interface
- Fixed an issue with the loading spinner rendering incorrectly in the comment period interface
- Fixed an issue where linking to the project details page from the news feed resulted in a blank target window
=> [EM-849] Fixing issues with scroll top behavior

src/app/comment-period/comment-period.component.html, src/app/comment-period/comment-period.component.scss, src/app/project-detail/project-detail.component.html, src/assets/styles/components/activity-feed.scss, src/assets/styles/components/spinner.scss
No Results indicators for the project activities and comment feeds.
=> [EM-918] Adding No Results indicators

src/app/app.module.ts, src/app/comment-period/comment-period.component.html, src/app/comment-period/comment-period.component.ts, src/app/project-detail/project-detail.component.ts, src/app/shared/shared.module.ts
Fixed scroll to top on pagination change.
Reorganized pipes to be part of the shared module, allowing them to be used across modules in the same app.
Tweaked project-details and comment-period views.
=> EM-917: Fixed scroll to top on pagination change.

src/app/news/news.component.html, src/app/project-detail/project-detail.component.html, src/app/project/project.component.html
Only the second commit is relevant. The first one is already included in [this pull request](https://github.com/bcgov/eao-public/pull/202) (I forgot that I had that change in my local dev branch when I created the feature branch).
=> EM-948: Fixed pagination issue when applying filters to table data.

src/app/comment-period/pcp-info-modal/pcp-info-modal.component.html, src/app/comment-period/submit-comment-modal/submit-comment-modal.component.html, src/app/comment-period/submit-comment-modal/submit-comment-modal.component.scss, src/app/comment-period/submit-comment-progress-modal/submit-comment-progress-modal.component.html
- Adding missing PDF links in the submit comment interface
- Added accepted file types to submit comment form
- Fixed an issue with the loading spinner positioning
=> [EM-927] Submit Comment Interface Fixes

src/app/news/news.component.html, src/app/news/news.component.spec.ts, src/app/news/news.component.ts, src/app/project-detail/project-detail.component.html, src/app/project-detail/project-detail.component.spec.ts, src/app/project-detail/project-detail.component.ts
Added logic to display "No results found" message when filtered content doesn't return any matches.
=> em-1007: Tweaks to displayed element count message.

src/app/comment-period/comment-period.component.spec.ts, src/app/comment-period/submit-comment-modal/submit-comment-modal.component.html, src/app/comment-period/submit-comment-modal/submit-comment-modal.ts
No tests for this change, we will need to refactor how this module is structured before we tackle them, since all the functions seem to be DOM-manipulation related.
=> EM-338: Fixed file upload type and size limit for comment attachments.

src/app/pipes/proper-case.pipe.spec.ts, src/app/pipes/proper-case.pipe.ts, src/app/project-detail/project-detail.component.html, src/app/project-detail/project-detail.component.spec.ts, src/app/project-detail/project-detail.component.ts, src/app/project/project.component.spec.ts, src/app/project/project.component.ts, src/app/shared/shared.module.ts, src/app/utils/string-helper.spec.ts, src/app/utils/string-helper.ts, src/assets/styles/components/activity-feed.scss, tslint.json
Added ProperCase pipe and helper, and applied to region and proponent.
=> EM-1011: Fix Region capitalization

package.json, src/app/app.component.html, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/app.module.ts
- Removed admin navigation from header. 
- Removed unused CookieService dependency.
=> EM-1002: Removed admin navigation from header.

src/app/home/home.component.scss, src/app/news/news.component.scss, src/app/project-detail/project-detail.component.scss, src/app/project/project.component.scss, src/assets/styles/components/buttons.scss, src/assets/styles/components/filter-bar.scss, src/assets/styles/components/lists.scss
Minor fixes / clean-up
- Slightly reduced font-size on the project names in the activities feed (easier read)
- Fixed hover states on the filter toggle buttons (desktop)
- Fixed an issue where the project contacts email was not wrapping
- Fixed layout on project page meta (name value pairs appear left/right).
- Tightened up the layout of information on the project list page (mobile)
=> [UI-Cleanup] Minor UI Fixes & Cleanup

README.md, src/app/map/core/map-config.service.ts, src/app/map/main-map/main-map.component.ts, src/app/map/support/map-utils.ts
Squashed commits:
EM-1099: Map GUI - Mouseover mine name
EM-1110: Porting Maps changes to EAO from MEM
Merge branch 'dev'
EM-1099: Map GUI - Mouseover mine name
EM-1110: Porting Maps changes to EAO from MEM
New:
EM-1099: Code review changes
src/app/map/main-map/main-map.component.ts:66
src/app/map/main-map/main-map.component.ts:71
src/app/map/support/map-utils.ts:58
=> EM-1099: Code review changes

src/app/comment-period/comment-period.component.html, src/app/comment-period/comment-period.component.scss, src/app/comment-period/comment-period.component.ts, src/app/models/comment.ts, src/app/services/api.spec.ts, src/app/services/api.ts, src/app/services/comment-period.service.ts
EM-1051: Proponent Response Prototype
EM-1096: Updated to call modified api that returns only published comments. update unit tests.
Code Review already performed against individual tickets.
=> Proponent Response Feature

src/app/map/project-map/project-map.component.ts
=> EM-1110: Porting MEM maps to EAO

src/app/project-detail/project-detail.component.html, src/assets/styles/components/lists.scss
Small changes to html skeleton for contacts in project page. Long email addresses are now handled with ellipsis
=> EM-1274: Contacts text breaking across the page

src/app/app.component.html, src/app/home/home.component.html
Added a home page button and find ea project drop down menu button that links to a filtered list of all open public comment periods.
=> EM-1253: Link to All open Public Comment Periods

README.md
readme updates with minio information
=> HOTFIX: eguide readme update

src/app/models/news.ts, src/app/project-detail/project-detail.component.spec.ts, src/app/project-detail/project-detail.component.ts
EM-1350: hidden PCPs are no longer added to news list count
EM-1350: fixed count of news items for project details page. Was counting hidden elements
=> EM-1350: Hidden news events are still counted

src/app/project-detail/project-detail.component.spec.ts
commented out effected banner tests temp
=> Banner functionality effected tests

src/app/project-detail/project-detail.component.ts
This is just a copy of part of the work from EM-266, to make the documents display inline, I had just left out one page.
=> EM-295 Public landing page doc download
